### ISSUE TITLE
Lista de Exercícios Desatualizada

### ISSUE THREAD

**Issue by RianKoja** [reinaldo-rosa-inpe/cap239#4]
[Lista_Completa_+_Trabalho_CAP239_2020.pdf](https://github.com/reinaldo-rosa-inpe/cap239/files/4658185/Lista_Completa_%2B_Trabalho_CAP239_2020.pdf)

A lista de exercícios no repositório contem instruções sobre o trabalho, porém os enunciados dos exercícios parecem incompletos em relação a essa versão (em anexo).

Att.,

**Comment by deniseiras** [comment]
> [Lista_Completa_+_Trabalho_CAP239_2020.pdf](https://github.com/reinaldo-rosa-inpe/cap239/files/4658185/Lista_Completa_%2B_Trabalho_CAP239_2020.pdf)
> 
> A lista de exercícios no repositório contem instruções sobre o trabalho, porém os enunciados dos exercícios parecem incompletos em relação a essa versão (em anexo).
> 
> Att.,

A lista anexada acima é a mesma do repositório. Provavelmente o anexo correto seria o deste comentário.
[Lista_CAP239_2020_Atualizada_e_com_Tabela.pdf](https://github.com/reinaldo-rosa-inpe/cap239/files/4658396/Lista_CAP239_2020_Atualizada_e_com_Tabela.pdf)

**Comment by RianKoja** [comment]
Adicionalmente, no exercício 8, há alguns erros de digitação/atualização:
-no exercício 8 fala-se para repetir o item 9.1, no exercício 9 o primeiro item é o 10.1
-No exercício 8.2, foi dito em aula que "Db8" na verdade seria referente a wavelet mãe "DOG"
-Foi comentado em aula que não se deveria fazer esse exercício para todas as séries temporais. Não recordo se a ideia seria escolher um único gerador ou executar para uma série de cada gerador. Por algum motivo o mapa de Henon causa problemas com a função `contourf` usada dentro do pacote `waipy`
